import { Platform, StyleSheet } from "react-native";
export const chatScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerCenter: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 12,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  headerInfo: {
    flex: 1,
  },
  headerName: {
    fontFamily: Platform.select({
      ios: "Rubik_700Bold",
      android: "Rubik_700Bold",
      default: "Rubik_700Bold",
    }),
    color: "#000000",
    fontSize: 16,
    marginBottom: 2,
  },
  headerCancelText: {
    fontSize: 16,
    color: "#EC9A15",
    fontWeight: "600",
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
  },
  headerActions: {
    flexDirection: "row",
    gap: 16,
  },
  headerActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  headerActionText: {
    fontSize: 16,
    color: "#EC9A15",
    fontWeight: "600",
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  onlineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontFamily: Platform.select({
      ios: "Rubik_400Regular",
      android: "Rubik_400Regular",
      default: "Rubik_400Regular",
    }),
    color: "#4CAF50",
    fontSize: 12,
  },
  messagesContainer: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
  },

  actionBar: {
    position: "absolute",
    alignSelf: "center",
    zIndex: 1000,
  },
  actionBarContent: {
    flexDirection: "row",
    backgroundColor: "#000",
    borderRadius: 24,
    paddingHorizontal: 4,
    paddingVertical: 4,
    gap: 4,
  },
  actionBarButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  actionBarButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  actionBarButtonDanger: {
    color: "#FF3B30",
  },
  reactionRow: {
    flexDirection: "row",
    backgroundColor: "#000",
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginTop: 8,
    gap: 8,
    alignSelf: "center",
  },
  reactionEmoji: {
    padding: 4,
  },
  reactionEmojiText: {
    fontSize: 20,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    gap: 8,
  },
  inputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 25,
    paddingHorizontal: 16,
    minHeight: 40,
    maxHeight: 100,
  },
  input: {
    flex: 1,
    fontFamily: Platform.select({
      ios: "Rubik_400Regular",
      android: "Rubik_400Regular",
      default: "Rubik_400Regular",
    }),
    color: "#000000",
    paddingVertical: 8,
    fontSize: 14,
  },
  micButton: {
    padding: 8,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#72777A",
    justifyContent: "center",
    alignItems: "center",
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  menuContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    minWidth: 150,
    alignSelf: "flex-end",
    marginTop: 60,
    marginRight: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  menuItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  menuItemText: {
    fontFamily: Platform.select({
      ios: "Rubik_400Regular",
      android: "Rubik_400Regular",
      default: "Rubik_400Regular",
    }),
    color: "#000000",
    fontSize: 14,
  },
  menuItemDanger: {
    color: "#FF3B30",
  },
  forwardScreenContainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  forwardScreenHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  forwardScreenTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000",
  },
  forwardChatList: {
    flex: 1,
  },
  forwardChatItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  forwardChatAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
  },
  forwardChatName: {
    flex: 1,
    fontSize: 16,
    color: "#000",
    fontWeight: "500",
  },
  forwardChatCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#EC9A15",
    justifyContent: "center",
    alignItems: "center",
  },
  forwardChatCheckText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  forwardBottomBar: {
    paddingHorizontal: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
  },
  forwardSendButton: {
    backgroundColor: "#EC9A15",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  forwardSendButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    color: "#72777A",
    fontSize: 14,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  emptyText: {
    color: "#72777A",
    fontSize: 14,
    textAlign: "center",
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
});
