import { StyleSheet, Dimensions, Platform } from "react-native";
const { width, height } = Dimensions.get("window");
export const fanSelfProfileScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#3C2610",
    },
    scrollContent: {
        paddingBottom: 100,
    },
    infoContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
    },
    socialLinksContainer: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 16,
        marginTop: -20,
        marginBottom: 20,
    },
    socialIconButton: {
        width: 44,
        height: 44,
        borderRadius: 22, // Makes it a perfect circle
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.15)",
    },
    gamifiedAvatarContainer: {
        alignItems: "center",
        width: "100%",
        paddingTop: 50,
        marginBottom: 24,
        position: "relative",
    },
    avatarGradientRing: {
        width: width * 0.42,
        height: width * 0.42,
        borderRadius: width * 0.21,
        padding: 4, // This acts as the border thickness!
        shadowColor: "#FFD700",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
        elevation: 10,
    },
    gamifiedProfileImage: {
        width: "100%",
        height: "100%",
        borderRadius: width * 0.21,
        borderWidth: 3,
        borderColor: "#3C2610", // Gives separation between the gradient and the photo
        resizeMode: "cover",
    },
    rankBadgeContainer: {
        position: "absolute",
        bottom: -12,
        backgroundColor: "#FFD700",
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 12,
        borderWidth: 3,
        borderColor: "#3C2610",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 6,
    },
    rankBadgeText: {
        color: "#3C2610",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 1.5,
    },

    socialPill: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.15)",
    },
    socialIcon: {
        fontSize: 14,
        marginRight: 6,
    },
    socialText: {
        color: "#fff",
        fontSize: 13,
        fontWeight: "600",
    },

    // --- Edit Modal Social Inputs ---
    socialInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#2a2a2a",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#444",
        paddingHorizontal: 12,
    },
    socialInputPrefix: {
        color: "#EC9A15",
        fontSize: 16,
        fontWeight: "700",
        marginRight: 8,
    },
    socialInput: {
        flex: 1,
        paddingVertical: 12,
        color: "#fff",
        fontSize: 14,
    },
    header: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
        zIndex: 100,
    },
    backButton: {
        width: 40,
        height: 40,
        justifyContent: "center",
    },
    menuButton: {
        width: 40,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
    },
    hamburgerIcon: {
        width: 24,
        height: 18,
        justifyContent: "space-between",
    },
    hamburgerLine: {
        width: 24,
        height: 3,
        backgroundColor: "#fff",
        borderRadius: 2,
    },
    fanCircleContainer: {
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        marginTop: height * 0.06,
        paddingTop: 30,
    },
    fanCircleShape: {
        width: width * 1,
        height: width * 0.9,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    fanProfileImage: {
        width: width * 0.6,
        height: width * 0.6,
        borderRadius: (width * 0.6) / 2,
        resizeMode: "cover",
    },
    fanCircleFrame: {
        width: width * 0.6,
        height: width * 0.6,
        borderRadius: (width * 0.6) / 2,
        borderWidth: 4,
        borderColor: "#EC9A15",
        position: "absolute",
        zIndex: 10,
    },
    contentContainer: {
        backgroundColor: "rgba(41, 33, 24, 1)",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderColor: "#000",
        borderWidth: 1,
        paddingTop: 10,
        marginTop: 5,
    },
    tabContainer: {
        flexDirection: "row",
        marginBottom: height * 0.025,
        paddingHorizontal: width * 0.125,
    },
    tabActive: {
        borderBottomWidth: 2,
        borderBottomColor: "#EC9A15",
    },
    tab: {
        flex: 1,
        paddingVertical: height * 0.012,
        alignItems: "center",
    },
    tabText: {
        fontSize: width * 0.04,
        color: "#9CA3AF",
    },
    activeTabText: {
        color: "#EC9A15",
    },
    gridContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        paddingHorizontal: 10,
        gap: 4,
    },
    gridItem: {
        borderRadius: 4,
        overflow: "hidden",
    },
    gridImage: {
        width: "100%",
        height: "100%",
        borderRadius: 4,
    },

    menuOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        justifyContent: "flex-start",
        alignItems: "flex-end",
    },
    menuContainer: {
        backgroundColor: "#1a1a1a",
        width: width * 0.8,
        height: "100%",
        paddingTop: Platform.OS === "ios" ? 60 : 40,
        shadowColor: "#000",
        shadowOffset: { width: -4, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
        elevation: 15,
        borderLeftWidth: 1,
        borderLeftColor: "rgba(236, 154, 21, 0.2)",
    },
    menuScrollView: {
        flex: 1,
        paddingBottom: 80,
    },
    menuProfileSection: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 24,
        paddingBottom: 12,
        paddingTop: 8,
    },
    menuProfileImage: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginRight: 16,
        borderWidth: 2,
        borderColor: "#EC9A15",
    },
    menuProfileNameRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
    },
    menuProfileName: {
        fontSize: 20,
        color: "#fff",
        fontWeight: "600",
        letterSpacing: 0.3,
    },
    menuVerifiedBadge: {
        marginLeft: 6,
    },
    menuDividerGold: {
        height: 2,
        backgroundColor: "rgba(236, 154, 21, 0.3)",
        marginHorizontal: 24,
        marginBottom: 12,
        borderRadius: 1,
    },
    menuSectionTitle: {
        fontSize: 12,
        color: "#EC9A15",
        paddingHorizontal: 24,
        paddingVertical: 8,
        textTransform: "uppercase",
        letterSpacing: 1.5,
        fontWeight: "700",
    },
    menuItem: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 24,
        marginHorizontal: 8,
        marginVertical: 1,
        borderRadius: 12,
        backgroundColor: "transparent",
    },
    menuItemText: {
        fontSize: 16,
        color: "#fff",
        marginLeft: 16,
        fontWeight: "500",
        letterSpacing: 0.2,
    },
    menuItemDisabled: {
        opacity: 0.5,
    },
    menuItemTextDisabled: {
        color: "#666",
    },
    menuIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: "rgba(236, 154, 21, 0.15)",
        justifyContent: "center",
        alignItems: "center",
    },
    menuItemWithBadge: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginLeft: 16,
    },

    verifiedBadgeInline: {
        marginLeft: 8,
    },
    notVerifiedText: {
        fontSize: 12,
        color: "#999",
        marginLeft: 8,
        fontWeight: "400",
    },

    menuDivider: {
        height: 1,
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        marginVertical: 12,
        marginHorizontal: 24,
    },
    logoutItem: {
        marginTop: 8,
        borderRadius: 12,
        marginHorizontal: 8,
    },
    logoutText: {
        color: "#FF6B6B",
    },
    // Edit Bio Modal Styles
    editBioOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    editBioContainer: {
        backgroundColor: "#1a1a1a",
        borderRadius: 15,
        width: "100%",
        maxWidth: 400,
        padding: 20,
    },
    editBioHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },

    editBioTitle: {
        fontSize: 22,
        color: "#fff",
    },
    editBioClose: {
        fontSize: 28,
        color: "#999",
    },
    editBioInput: {
        backgroundColor: "#2a2a2a",
        borderRadius: 10,
        padding: 15,
        color: "#fff",
        fontSize: 16,
        minHeight: 100,
        textAlignVertical: "top",
        borderWidth: 1,
        borderColor: "#444",
    },
    bioCharCount: {
        color: "#999",
        fontSize: 12,
        textAlign: "right",
        marginTop: 8,
    },

    editLabel: {
        color: "#fff",
        fontSize: 14,
        marginBottom: 8,
        fontFamily: "Rubik_500Medium",
    },
    threeWordsEditContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#2a2a2a",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#444",
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    threeWordsEditInput: {
        flex: 1,
        paddingHorizontal: 8,
        paddingVertical: 12,
        color: "#fff",
        fontSize: 14,
    },
    threeWordsEditSeparator: {
        color: "#EC9A15",
        fontSize: 16,
        paddingHorizontal: 4,
        fontFamily: "Rubik_500Medium",
    },
    editBioButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 20,
        gap: 10,
    },
    editBioButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    cancelButton: {
        backgroundColor: "#333",
    },
    cancelButtonText: {
        color: "#fff",
        fontSize: 16,
    },
    saveButton: {
        backgroundColor: "#EC9A15",
    },
    saveButtonText: {
        color: "#fff",
        fontSize: 16,
    },
    // Level-Up Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        justifyContent: "center",
        alignItems: "center",
    },
    levelUpModalContainer: {
        width: "90%",
        maxWidth: 400,
    },
    levelUpModalContent: {
        backgroundColor: "#3C2610",
        borderRadius: 20,
        padding: 24,
        borderWidth: 2,
        borderColor: "#EC9A15",
    },
    levelUpModalTitle: {
        color: "#EC9A15",
        fontSize: 24,
        fontWeight: "700",
        textAlign: "center",
        marginBottom: 24,
    },
    levelUpRulesContainer: {
        marginBottom: 20,
    },
    levelUpRuleItem: {
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(236, 154, 21, 0.2)",
    },
    levelUpRuleText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "500",
    },
    levelUpModalNote: {
        color: "#EC9A15",
        fontSize: 14,
        textAlign: "center",
        fontStyle: "italic",
        marginBottom: 24,
        paddingHorizontal: 10,
    },
    levelUpModalCloseButton: {
        backgroundColor: "#EC9A15",
        borderRadius: 10,
        paddingVertical: 14,
        alignItems: "center",
    },
    levelUpModalCloseButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "700",
    },
});
