import { Dimensions, StyleSheet } from "react-native";
const { width, height } = Dimensions.get("window");
export const liveCompetitionStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#3C2610",
    },
    stickyBottomCTA: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: 16,
        zIndex: 1000,
        paddingTop: 24,
        backgroundColor: "rgba(60, 38, 16, 0.95)",
        borderTopWidth: 1,
        borderTopColor: "rgba(255, 255, 255, 0.05)",
    },
    heroPrizeContainer: {
        alignItems: "center",
        paddingVertical: 16,
        backgroundColor: "rgba(255, 215, 0, 0.05)", // Very subtle gold glow
        borderRadius: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "rgba(255, 215, 0, 0.15)",
    },
    heroPrizeLabel: {
        fontSize: 12,
        color: "#EC9A15",
        letterSpacing: 1.5,
        fontWeight: "600",
        marginBottom: 4,
    },
    heroPrizeAmount: {
        fontSize: 36,
        color: "#FFD700",
        fontWeight: "800",
        textShadowColor: "rgba(255, 215, 0, 0.3)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 10,
    },
    podiumContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 8,
        paddingVertical: 8,
    },
    podiumPill: {
        flex: 1,
        backgroundColor: "rgba(255, 215, 0, 0.03)",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 8,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 215, 0, 0.1)",
    },
    specsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.2)", // Slight inset look
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginVertical: 4,
    },
    specBox: {
        flex: 1,
        alignItems: "flex-start",
    },
    specHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 6,
        gap: 6,
    },
    specIcon: {
        fontSize: 14,
    },
    specLabel: {
        color: "#999",
        fontSize: 12,
        textTransform: "uppercase",
        letterSpacing: 0.5,
        fontWeight: "600",
    },
    specValue: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "600",
    },
    specVerticalDivider: {
        width: 1,
        height: "80%",
        backgroundColor: "#4a3a2a",
        marginHorizontal: 16,
    },
    freeBadge: {
        backgroundColor: "rgba(34, 197, 94, 0.15)", // Translucent neon green
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "rgba(34, 197, 94, 0.4)",
    },
    freeBadgeText: {
        color: "#22C55E", // Solid neon green text
        fontSize: 12,
        fontWeight: "800",
        letterSpacing: 1,
    },
    progressBarContainer: {
        height: 6,
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        borderRadius: 3,
        marginTop: 12,
        overflow: "hidden",
    },
    progressBarFill: {
        height: "100%",
        backgroundColor: "#FF0055", // A vibrant neon red/pink
        borderRadius: 3,
        shadowColor: "#FF0055",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 4, // Android glow
    },
    missionBriefingCard: {
        backgroundColor: "#2A1A0B",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#4A3A2A",
        overflow: "hidden",
        marginTop: 4,
    },
    missionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
        backgroundColor: "rgba(255, 255, 255, 0.03)",
    },
    missionTitleRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    missionIcon: {
        fontSize: 20,
    },
    missionTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 0.5,
    },
    chevron: {
        color: "#EC9A15",
        fontSize: 14,
    },
    missionContent: {
        padding: 16,
        paddingTop: 0,
    },
    missionSectionTitle: {
        fontSize: 12,
        color: "#EC9A15",
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 1,
        marginTop: 16,
        marginBottom: 8,
    },
    missionText: {
        fontSize: 14,
        color: "#C7C7C7",
        lineHeight: 22,
        flex: 1,
    },
    missionDivider: {
        height: 1,
        backgroundColor: "#4A3A2A",
        marginTop: 20,
    },
    rulesList: {
        gap: 10,
    },
    ruleBulletRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
    },
    ruleBullet: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: "#FF0055", // Neon red/pink dot
        marginTop: 8,
    },
    leaderboardTitleContainer: {
        alignItems: "center",
        marginBottom: 8,
        marginTop: 16,
    },
    leaderboardMainTitle: {
        fontSize: 20,
        color: "#FFD700",
        fontWeight: "800",
        letterSpacing: 1.5,
        textShadowColor: "rgba(255, 215, 0, 0.4)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 8,
    },
    leaderboardSubTitle: {
        fontSize: 13,
        color: "#C7C7C7",
        marginTop: 4,
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    podiumMedal: {
        fontSize: 24,
        marginBottom: 4,
    },
    podiumTextContainer: {
        alignItems: "center",
    },
    podiumPosition: {
        fontSize: 11,
        color: "#999",
        fontWeight: "500",
        marginBottom: 2,
    },
    podiumAmount: {
        fontSize: 14,
        color: "#fff",
        fontWeight: "700",
    },
    socialProofContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
    },
    avatarPileContainer: {
        flex: 1,
        flexDirection: "column",
        marginTop: 4,
        gap: 8,
    },
    avatars: {
        flexDirection: "row",
        alignItems: "center",
    },
    pileAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 2,
        borderColor: "#40301F", // Matches the card background to create a cutout effect
    },
    battlingText: {
        color: "#C7C7C7",
        fontSize: 12,
    },
    battlingCount: {
        color: "#EC9A15", // Punchy orange
        fontWeight: "700",
        fontSize: 13,
    },
    starFlexBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 215, 0, 0.08)", // Slight gold tint
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(255, 215, 0, 0.2)",
        gap: 10,
    },
    starFlexIcon: {
        fontSize: 22,
    },
    starFlexValue: {
        color: "#FFD700",
        fontSize: 16,
        fontWeight: "800",
    },
    starFlexLabel: {
        color: "#EC9A15",
        fontSize: 10,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    buttonRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 12,
    },
    fullWidthButton: {
        width: "100%",
        height: 56,
        borderRadius: 28,
        shadowColor: "#FFD700",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 8, // Adds a nice glow on Android
    },
    halfButton: {
        flex: 1,
        height: 56,
        borderRadius: 28,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    gradientFill: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 28,
    },
    ctaText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "700",
        letterSpacing: 0.5,
    },
    disabledButton: {
        backgroundColor: "#2A1A0B", // Dark, muted version of your theme color
        borderWidth: 1,
        borderColor: "#4A3A2A",
        justifyContent: "center",
        alignItems: "center",
        elevation: 0, // Remove shadow so it looks "flat"
    },
    disabledText: {
        color: "#888",
        fontSize: 14,
        fontWeight: "600",
    },
    topDancersContainer: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "flex-end",
        gap: width * 0.04,
        paddingVertical: 15,
        paddingHorizontal: width * 0.02,
        marginTop: 30,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingTop: 50,
        paddingBottom: 16,
        backgroundColor: "#3C2610",
    },
    viewAllButton: {
        borderRadius: 16,
        width: "100%",
        padding: 16,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#ec9a15",
    },
    viewAllText: {
        color: "#f0f0f0",
        fontSize: 16,
    },
    headerButton: {
        width: 40,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
    },
    headerTitle: {
        flex: 1,
        fontSize: 18,
        color: "#fff",
        textAlign: "center",
        marginHorizontal: 8,
    },
    scrollView: {
        flex: 1,
    },
    bannerContainer: {
        position: "relative",
        width: width,
        height: height * 0.3,
    },
    bannerImage: {
        width: "100%",
        height: "100%",
        resizeMode: "cover",
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
    },
    bannerGradient: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        height: "50%",
    },
    liveBadge: {
        position: "absolute",
        top: 16,
        left: 16,
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 0, 0, 0.9)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        gap: 6,
    },
    liveDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#fff",
    },
    liveBadgeText: {
        color: "#fff",
        fontSize: 12,
        letterSpacing: 1,
    },
    infoSection: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: "#40301F",
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
    },
    infoRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    categoryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 12,
    },
    categoryText: {
        fontSize: 20,
        color: "#fff",
        fontWeight: "700",
        flex: 1,
    },
    presenterText: {
        fontSize: 13,
        color: "#fff",
    },
    votingRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    votingText: {
        fontSize: 14,
        color: "#FF6B35",
        flex: 1,
    },
    section: {
        paddingHorizontal: 16,
        marginBottom: 12,
        marginTop: 12,
        gap: 10,
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    sectionTitle: {
        fontSize: 18,
        color: "#fff",
        marginBottom: 12,
    },
    viewAllLink: {
        fontSize: 14,
        color: "#FF6B35",
    },
    card: {
        backgroundColor: "#40301F",
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: "#4a3a2a",
    },
    detailRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingVertical: 6,
    },
    detailLabel: {
        fontSize: 14,
        color: "#999",
    },
    detailValue: {
        fontSize: 14,
        color: "#fff",
    },
    prizeSection: {
        marginBottom: 4,
    },
    prizeSectionLabel: {
        fontSize: 11,
        color: "#999",
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    prizeList: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    prizeListRight: {
        flexDirection: "column",
        alignItems: "flex-end",
        gap: 4,
    },
    prizeItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255,140,0,0.1)",
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        gap: 6,
    },
    prizePosition: {
        fontSize: 12,
        color: "#999",
    },
    prizeAmount: {
        fontSize: 14,
        color: "#FFD700",
    },
    prizeAmountRight: {
        fontSize: 13,
        color: "#EC9A15",
        fontWeight: "500",
    },
    statsGrid: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 4,
    },
    statBox: {
        flex: 1,
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 8,
        backgroundColor: "rgba(255,140,0,0.08)",
        borderRadius: 10,
        marginHorizontal: 4,
    },
    statBoxLabel: {
        fontSize: 11,
        color: "#999",
        marginBottom: 4,
        letterSpacing: 0.5,
    },
    statBoxValue: {
        fontSize: 18,
        color: "#FFD700",
    },
    detailRowCompact: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingVertical: 8,
    },
    detailLabelCompact: {
        fontSize: 13,
        color: "#C7C7C7",
        flex: 1,
    },
    detailValueCompact: {
        fontSize: 13,
        color: "#EC9A15",
        flex: 1.5,
        textAlign: "right",
        lineHeight: 18,
        fontWeight: "500",
    },
    divider: {
        height: 1,
        backgroundColor: "#4a3a2a",
        marginVertical: 6,
    },
    ruleSection: {
        marginBottom: 12,
    },
    ruleRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingVertical: 8,
    },
    top10Section: {
        paddingHorizontal: 16,
        marginBottom: 0,
        marginTop: 14,
        alignItems: "center",
    },
    ruleHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
        gap: 8,
    },
    ruleIcon: {
        fontSize: 18,
    },
    ruleItem: {
        marginBottom: 10,
    },
    ruleLabel: {
        fontSize: 14,
        color: "#C7C7C7",
        flex: 1,
    },
    ruleText: {
        fontSize: 14,
        color: "#C7C7C7",
        lineHeight: 20,
        flex: 2,
        textAlign: "right",
    },
    ruleDivider: {
        height: 1,
        backgroundColor: "#4a3a2a",
        marginVertical: 12,
    },
    votingOpenButton: {
        borderRadius: 10,
        overflow: "hidden",
        marginTop: 8,
    },
    votingOpenButtonGradient: {
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    votingOpenButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        letterSpacing: 0.5,
    },
    leaderboardItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 12,
        backgroundColor: "#2a2a2a",
        borderRadius: 10,
        marginBottom: 8,
    },
    leaderboardLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        flex: 1,
    },
    rankText: {
        fontSize: 16,
        color: "#fff",
        width: 25,
        textAlign: "left",
    },
    participantImage: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        borderWidth: 2,
        borderColor: "#EC9A15",
    },
    participantUsername: {
        fontSize: 14,
        color: "#fff",
        fontWeight: "500",
    },
    participantVotes: {
        fontSize: 12,
        color: "#999",
    },
    medalContainer: {
        marginLeft: 8,
    },
    entriesScroll: {
        marginTop: 8,
    },
    entriesContainer: {
        marginTop: 8,
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: 10,
    },
    entryCard: {
        width: width * 0.4,
        marginRight: 12,
        backgroundColor: "#40301F",
        borderRadius: 12,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "#4a3a2a",
    },
    entryCardVertical: {
        backgroundColor: "#40301F",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#4a3a2a",
        overflow: "hidden",
        width: (width - 32 - 10) / 2, // 32 for padding, 10 for gap, divided by 2
        marginBottom: 10,
    },
    entryThumbnailVertical: {
        width: "100%",
        height: width * 0.5,
        resizeMode: "cover",
    },
    entryCardContent: {
        flexDirection: "column",
        padding: 12,
        gap: 10,
    },
    entryThumbnail: {
        width: "100%",
        height: width * 0.5,
        resizeMode: "cover",
    },
    entryInfo: {
        padding: 12,
    },
    entryUsername: {
        fontSize: 13,
        color: "#fff",
        fontWeight: "500",
        marginBottom: 4,
    },
    entryVotes: {
        fontSize: 12,
        color: "#999",
    },
    voteButton: {
        backgroundColor: "#EC9A15",
        paddingVertical: 8,
        borderRadius: 8,
        alignItems: "center",
    },
    voteButtonSmall: {
        backgroundColor: "#EC9A15",
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    voteButtonDisabled: {
        backgroundColor: "#555",
    },
    voteButtonText: {
        color: "#fff",
        fontSize: 13,
    },
    pendingContainer: {
        marginTop: 16,
        padding: 20,
        backgroundColor: "rgba(255,140,0,0.1)",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(255,140,0,0.3)",
        alignItems: "center",
    },
    pendingBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(255,140,0,0.2)",
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        marginBottom: 16,
    },
    pendingBadgeText: {
        color: "#FF8C00",
        fontSize: 13,
        letterSpacing: 0.5,
    },
    pendingTitle: {
        fontSize: 18,
        color: "#fff",
        marginBottom: 8,
        textAlign: "center",
    },
    pendingSubtitle: {
        fontSize: 14,
        color: "#C7C7C7",
        textAlign: "center",
        lineHeight: 20,
        marginBottom: 20,
    },
    pendingInfo: {
        width: "100%",
        gap: 12,
    },
    pendingInfoText: {
        fontSize: 13,
        color: "#999",
        lineHeight: 20,
    },
    approvedContainer: {
        marginTop: 16,
        padding: 20,
        backgroundColor: "rgba(34,197,94,0.1)",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(34,197,94,0.3)",
        alignItems: "center",
    },
    approvedBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "rgba(34,197,94,0.2)",
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        marginBottom: 16,
    },
    approvedBadgeText: {
        color: "#22C55E",
        fontSize: 13,
        letterSpacing: 0.5,
    },
    approvedTitle: {
        fontSize: 18,
        color: "#fff",
        marginBottom: 8,
        textAlign: "center",
    },
    approvedSubtitle: {
        fontSize: 14,
        color: "#C7C7C7",
        textAlign: "center",
        lineHeight: 20,
    },
    statsRow: {
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        paddingVertical: 12,
        backgroundColor: "rgba(255,140,0,0.05)",
        borderRadius: 12,
        marginVertical: 8,
    },
    statItem: {
        alignItems: "center",
        flex: 1,
    },
    statLabel: {
        fontSize: 12,
        color: "#999",
        marginBottom: 4,
    },
    statValue: {
        fontSize: 18,
        color: "#FFD700",
    },
    statDivider: {
        width: 1,
        height: 30,
        backgroundColor: "#333",
    },
    statsOverlay: {
        position: "absolute",
        bottom: 12,
        right: 16,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    statItemOverlay: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 18,
        backdropFilter: "blur(10px)",
    },
    statText: {
        color: "#fff",
        fontSize: 14,
    },
    // Share Modal Styles
    shareModal: {
        backgroundColor: "#1a1a1a",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingBottom: 40,
        maxHeight: height * 0.6,
    },
    handleBar: {
        width: 40,
        height: 4,
        backgroundColor: "#666",
        borderRadius: 2,
        alignSelf: "center",
        marginTop: 8,
        marginBottom: 16,
    },
    shareHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingBottom: 16,
    },
    shareHeaderTitle: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "700",
    },
    closeButton: {
        color: "#fff",
        fontSize: 24,
        fontWeight: "300",
    },
    shareOptionsList: {
        paddingVertical: 10,
    },
    shareOptionsContent: {
        paddingHorizontal: 20,
    },
    shareOption: {
        alignItems: "center",
        marginRight: 20,
        width: 70,
    },
    shareOptionIconCircle: {
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 8,
    },
    shareIconImage: {
        width: 24,
        height: 24,
    },
    shareOptionName: {
        color: "#fff",
        fontSize: 12,
        textAlign: "center",
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: "#3C2610",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: height * 0.8,
        paddingTop: 20,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#4a3a2a",
    },
    modalTitle: {
        fontSize: 20,
        color: "#fff",
        fontWeight: "700",
    },
    modalCloseButton: {
        width: 32,
        height: 32,
        justifyContent: "center",
        alignItems: "center",
    },
    modalCloseText: {
        fontSize: 24,
        color: "#fff",
        fontWeight: "300",
    },
    modalScrollView: {
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
});
