import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");
export const participantSelfProfileScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#3C2610",
    },
    rankCardContainer: {
        backgroundColor: "rgba(255, 255, 255, 0.04)", // Changed from black to faint white
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "rgba(236, 154, 21, 0.3)",
        // Remove the heavy black shadow so it blends smoother
        shadowColor: "#EC9A15",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
    },
    progressContainer: {
        marginTop: 10,
    },
    progressHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 8,
    },
    progressText: {
        color: "#EC9A15",
        fontSize: 12,
        fontWeight: "700",
        fontFamily: "Rubik_500Medium", // Adjust if you use a different font family name
    },
    progressFraction: {
        color: "#9CA3AF",
        fontSize: 12,
    },
    progressBarBackground: {
        height: 8,
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        borderRadius: 4,
        overflow: "hidden",
    },
    progressBarFill: {
        height: "100%",
        borderRadius: 4,
    },
    progressHint: {
        color: "#9CA3AF",
        fontSize: 11,
        fontStyle: "italic",
        marginTop: 8,
        textAlign: "center",
    },

    // --- Achievements / Trophy Case ---
    achievementsContainer: {
        paddingHorizontal: 20,
        marginBottom: 24,
    },
    achievementsTitle: {
        color: "#9CA3AF",
        fontSize: 13,
        fontWeight: "700",
        letterSpacing: 1.2,
        textTransform: "uppercase",
        marginBottom: 12,
    },
    badgePlaceholder: {
        width: 54,
        height: 54,
        borderRadius: 27,
        backgroundColor: "#2a2a2a",
        borderWidth: 1,
        borderColor: "#EC9A15",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#EC9A15",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
    },
    scrollContent: {
        paddingBottom: 100,
    },
    header: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
        zIndex: 100,
    },

    gamifiedAvatarContainer: {
        alignItems: "center",
        width: "100%",
        paddingTop: 75,
        marginBottom: 10,
        position: "relative",
    },
    avatarGradientRing: {
        width: width * 0.42,
        height: width * 0.42,
        borderRadius: width * 0.21,
        padding: 4, // This acts as the border thickness!
        shadowColor: "#FFD700",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
        elevation: 10,
    },
    gamifiedProfileImage: {
        width: "100%",
        height: "100%",
        borderRadius: width * 0.21,
        borderWidth: 3,
        borderColor: "#3C2610", // Gives separation between the gradient and the photo
        resizeMode: "cover",
    },
    rankBadgeContainer: {
        position: "absolute",
        bottom: -12,
        backgroundColor: "#FFD700",
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 12,
        borderWidth: 3,
        borderColor: "#3C2610",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 6,
    },
    rankBadgeText: {
        color: "#3C2610",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 1.5,
    },
    socialPill: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.15)",
    },
    socialIcon: {
        fontSize: 14,
        marginRight: 6,
    },
    socialText: {
        color: "#fff",
        fontSize: 13,
        fontWeight: "600",
    },

    // --- Edit Modal Social Inputs ---
    socialInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#2a2a2a",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#444",
        paddingHorizontal: 12,
    },
    // --- Social Links ---
    socialLinksContainer: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 16,
        marginTop: -20,
        marginBottom: 20,
    },
    socialIconButton: {
        width: 44,
        height: 44,
        borderRadius: 22, // Makes it a perfect circle
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.15)",
    },
    socialInputPrefix: {
        color: "#EC9A15",
        fontSize: 16,
        fontWeight: "700",
        marginRight: 8,
    },
    socialInput: {
        flex: 1,
        paddingVertical: 12,
        color: "#fff",
        fontSize: 14,
    },
    backButton: {
        width: 40,
        height: 40,
        justifyContent: "center",
    },
    menuButton: {
        width: 40,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
    },
    hamburgerIcon: {
        width: 24,
        height: 18,
        justifyContent: "space-between",
    },
    hamburgerLine: {
        width: 24,
        height: 3,
        backgroundColor: "#fff",
        borderRadius: 2,
    },
    starContainer: {
        alignItems: "center",
        width: "100%",
        paddingTop: 40,
    },
    starShape: {
        width: width * 1,
        height: width * 0.9,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    starImage: {
        width: "100%",
        height: "100%",
        position: "absolute",
        resizeMode: "cover",
        zIndex: 10,
    },
    profileImage: {
        width: width * 0.5,
        height: width * 0.5,
        marginTop: -height * 0.012,
    },
    contentContainer: {
        backgroundColor: "rgba(41, 33, 24, 1)",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderColor: "#000",
        borderWidth: 1,
        paddingTop: 20,
        marginTop: -10,
    },
    tabContainer: {
        flexDirection: "row",
        marginBottom: height * 0.025,
        paddingHorizontal: width * 0.125,
    },
    tabActive: {
        borderBottomWidth: 2,
        borderBottomColor: "#EC9A15",
    },
    tab: {
        flex: 1,
        paddingVertical: height * 0.012,
        alignItems: "center",
    },
    tabText: {
        fontSize: width * 0.04,
        color: "#9CA3AF",
    },
    activeTabText: {
        color: "#EC9A15",
    },
    gridContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        paddingHorizontal: 10,
        gap: 4,
    },
    gridItem: {
        borderRadius: 4,
        overflow: "hidden",
    },
    gridImage: {
        width: "100%",
        height: "100%",
        borderRadius: 4,
    },

    // --- Edit Bio Modal Styles ---
    editBioOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    editBioContainer: {
        backgroundColor: "#1a1a1a",
        borderRadius: 15,
        width: "100%",
        maxWidth: 400,
        padding: 20,
    },
    editBioHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    editBioTitle: {
        fontSize: 22,
        color: "#fff",
    },
    editBioClose: {
        fontSize: 28,
        color: "#999",
    },
    editBioInput: {
        backgroundColor: "#2a2a2a",
        borderRadius: 10,
        padding: 15,
        color: "#fff",
        fontSize: 16,
        minHeight: 100,
        textAlignVertical: "top",
        borderWidth: 1,
        borderColor: "#444",
    },
    bioCharCount: {
        color: "#999",
        fontSize: 12,
        textAlign: "right",
        marginTop: 8,
    },
    editLabel: {
        color: "#fff",
        fontSize: 14,
        marginBottom: 8,
        fontFamily: "Rubik_500Medium",
    },
    threeWordsEditContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#2a2a2a",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#444",
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    threeWordsEditInput: {
        flex: 1,
        paddingHorizontal: 8,
        paddingVertical: 12,
        color: "#fff",
        fontSize: 14,
    },
    threeWordsEditSeparator: {
        color: "#EC9A15",
        fontSize: 16,
        paddingHorizontal: 4,
        fontFamily: "Rubik_500Medium",
    },
    editBioButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 20,
        gap: 10,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: "#333",
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    cancelButtonText: {
        color: "#fff",
        fontSize: 16,
    },
    saveButton: {
        flex: 1,
        backgroundColor: "#EC9A15",
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    saveButtonText: {
        color: "#fff",
        fontSize: 16,
    },

    // --- Level-Up Modal Styles ---
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        justifyContent: "center",
        alignItems: "center",
    },
    levelUpModalContainer: {
        width: "90%",
        maxWidth: 400,
    },
    levelUpModalContent: {
        backgroundColor: "#3C2610",
        borderRadius: 20,
        padding: 24,
        borderWidth: 2,
        borderColor: "#EC9A15",
    },
    levelUpModalTitle: {
        color: "#EC9A15",
        fontSize: 24,
        fontWeight: "700",
        textAlign: "center",
        marginBottom: 24,
    },
    levelUpRulesContainer: {
        marginBottom: 20,
    },
    levelUpRuleItem: {
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(236, 154, 21, 0.2)",
    },
    levelUpRuleText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "500",
    },
    levelUpModalNote: {
        color: "#EC9A15",
        fontSize: 14,
        textAlign: "center",
        fontStyle: "italic",
        marginBottom: 24,
        paddingHorizontal: 10,
    },
    levelUpModalCloseButton: {
        backgroundColor: "#EC9A15",
        borderRadius: 10,
        paddingVertical: 14,
        alignItems: "center",
    },
    levelUpModalCloseButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "700",
    },
});
