import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  header: {
    backgroundColor: "#111",
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 40,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchBar: {
    flex: 1,
    backgroundColor: "#222",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: "#fff",
    fontSize: 14,
    fontFamily: "System",
  },
  importButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FF006E",
    justifyContent: "center",
    alignItems: "center",
  },
  closeButton: {
    width: 36,
    height: 36,
    justifyContent: "center",
    alignItems: "center",
  },
  closeButtonText: {
    fontSize: 28,
    color: "#fff",
    lineHeight: 32,
  },
  tabScroll: {
    backgroundColor: "#000",
    borderBottomWidth: 1,
    borderBottomColor: "#222",
    maxHeight: 48,
  },
  tabContainer: {
    paddingHorizontal: 12,
    gap: 8,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  tab: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#333",
    flexShrink: 1,
    height: "auto",
  },
  tabActive: {
    backgroundColor: "#fff",
    borderColor: "#fff",
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#999",
  },
  tabLabelActive: {
    color: "#000",
  },
  content: {
    flex: 1,
  },
  featuredBanner: {
    height: 200,
    margin: 16,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#111",
  },
  featuredCoverImage: {
    width: "100%",
    height: "100%",
  },
  featuredOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  featuredTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  featuredArtist: {
    fontSize: 12,
    color: "#ccc",
  },
  trackItem: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1a1a1a",
  },
  trackItemSelected: {
    backgroundColor: "rgba(255, 0, 110, 0.1)",
  },
  trackThumbnail: {
    width: 48,
    height: 48,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#111",
  },
  trackCoverImage: {
    width: "100%",
    height: "100%",
  },
  trackPlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1a1a1a",
  },
  trackInfo: {
    flex: 1,
    gap: 4,
  },
  trackTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },
  trackMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  trackArtist: {
    fontSize: 12,
    color: "#999",
    flex: 1,
  },
  trackUsage: {
    fontSize: 12,
    color: "#666",
  },
  trackActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  trackDuration: {
    fontSize: 12,
    color: "#666",
    minWidth: 32,
    textAlign: "right",
  },
  saveButton: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 300,
  },
  loadingFooter: {
    paddingVertical: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 14,
    color: "#666",
  },
});
