import { StyleSheet, Platform, Dimensions } from "react-native";
const { width } = Dimensions.get("window");
export const styles = StyleSheet.create({
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "flex-start",
    alignItems: "flex-end",
  },
  rankBadgeText: {
    fontSize: 14,
    color: "#EC9A15",
    fontWeight: "700",
    marginLeft: "auto",
  },
  menuDivider: {
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    marginVertical: 12,
    marginHorizontal: 24,
  },
  logoutItem: {
    marginTop: 8,
    borderRadius: 12,
    marginHorizontal: 8,
  },
  logoutText: {
    color: "#FF6B6B",
  },
  menuContainer: {
    backgroundColor: "#1a1a1a",
    width: width * 0.8,
    height: "100%",
    paddingTop: Platform.OS === "ios" ? 60 : 40,
    shadowColor: "#000",
    shadowOffset: { width: -4, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: 15,
    borderLeftWidth: 1,
    borderLeftColor: "rgba(236, 154, 21, 0.2)",
  },
  menuScrollView: {
    flex: 1,
    paddingBottom: 80,
  },
  menuProfileSection: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingBottom: 12,
    paddingTop: 8,
  },
  menuProfileImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 16,
    borderWidth: 2,
    borderColor: "#EC9A15",
  },
  menuProfileNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  menuProfileName: {
    fontSize: 20,
    color: "#fff",
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  menuVerifiedBadge: {
    marginLeft: 6,
  },
  menuDividerGold: {
    height: 2,
    backgroundColor: "rgba(236, 154, 21, 0.3)",
    marginHorizontal: 24,
    marginBottom: 12,
    borderRadius: 1,
  },
  menuSectionTitle: {
    fontSize: 12,
    color: "#EC9A15",
    paddingHorizontal: 24,
    paddingVertical: 8,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    fontWeight: "700",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginHorizontal: 8,
    marginVertical: 1,
    borderRadius: 12,
    backgroundColor: "transparent",
  },
  menuItemText: {
    fontSize: 16,
    color: "#fff",
    marginLeft: 16,
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  menuItemDisabled: {
    opacity: 0.5,
  },
  menuItemTextDisabled: {
    color: "#666",
  },
  menuIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "rgba(236, 154, 21, 0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  menuItemWithBadge: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 16,
  },
});
